version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9-stretch

    branches:
      only:
        # Whitelist branches to build for.
        - master
        - /v\d+.*\-branch/
    steps:
      # Checkout repo & subs:
      - checkout

      # Get npm cache:
      - restore_cache:
          key: npm

      # Build steps:
      - run: cd admin && npm install
      - run: cd admin && npm run build

      # Make fast:
      - save_cache:
          key: npm
          paths:
            - ~/.npm

      # Run the deploy:
      - deploy:
          command: .circleci/deploy.sh
